[sw/bootloader] add TWI boot option
stnolting/neorv32 pull request #1108
Opened 2024-11-28 10:34 UTC by LukasP46

Add ability to read program from TWI (also known as I2C) memory like common EEPROMs with one address byte.

2024-12-03 20:55 UTC, stnolting commented
> Add ability to read program from TWI

Nice! Thank you very much!

> The bootloader gets to big if all options are enables. 

Oh I know this problem... 🙈
How much more ROM do you need for your modified bootloader?

> How should we handle this? Maybe disable TWI by default but add an additional test where SPI is disabled instead?

I was thinking about rewriting the bootloader in plain assembly... But to be honest, I'm too lazy for that... 😅

So yes, we could disable the TWI option by default and let the user decide if this is a relevant feature.

2024-12-04 08:57 UTC, LukasP46 commented
> How much more ROM do you need for your modified bootloader?

`Memory utilization:
   text    data     bss     dec     hex filename
   4456       0       8    4464    1170 main.elf`

> I was thinking about rewriting the bootloader in plain assembly... But to be honest, I'm too lazy for that... 😅

~~too lazy~~ not crazy
Surely it can be done, but it sounds really time consuming and rather hard to debug (and contribute to).

I actually use the C ISA extension so the bootloader is always small enough, but I guess I'll change the default and then the user can enable it if needed. I would actually suggest changing the warning as well and recommend recompiling the bootloader for each processor to enable a potentially smaller bootloader, what do you think?

2024-12-04 09:59 UTC, LukasP46 commented
While writing to the TWI memory via the bootloader is not planned, I will probably upload a Python script to flash via an USB I2C adapter.

2024-12-11 08:53 UTC, LukasP46 commented
> That's a good solution! But I would recommend to provide the pre-built bootloader image compiled with the minimal ISA options only - so it is compatible to any ISA configuration.

I agree, the pre-built should be compatible with any (but E currently) ISA configuration. But we could encourage the user to build the bootloader to their needs and ISA.

> Which warning?

This one in `bootloader.c`:
```
/**********************************************************************//**
 * Sanity check: Base RV32I ISA only!
 **************************************************************************/
#if defined __riscv_atomic || defined __riscv_a || __riscv_b || __riscv_compressed || defined __riscv_c || defined __riscv_mul || defined __riscv_m
  #warning In order to allow the bootloader to run on *any* CPU configuration it should be compiled using the base rv32i ISA only.
#endif
```

But actually I'm fine with it, because the first part says _to allow_, which actually implies _if you need it_...

> Btw, we have already enabled link-time-optimization and Os as compile-time switches. I am not sure if there is anything more we could do to further shrink the bootloader.

Probably not? [`-Oz`](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Oz) is even more aggressive, but is currently the same size as `-Os`.

> However, maybe it is worth a try to compile the bootloader with the absolute minimal ISA configuration which is rv32e. The E ISA extension only provides 16 x registers. Maybe the overhead of register spilling could be reduced by this?! 

I'll look into it. This would also have the advantage that the bootloader would actually work on all ISA configurations.

> I think we could re-use parts of the "SPI write" code?

Probably yes? Unfortunately I don't have a use case at the moment, but I keep it in mind. Probably not in this PR though. Some other bootloader extensions have a higher priority, you'll see :)

> I just scanned your code briefly, but I think you are using a fixed number of address bytes for accessing the TWI flash, right? Maybe we could also make this configurable just like we did for the SPI accesses.

I agree, I'll add that one!

2024-12-11 20:15 UTC, stnolting commented
> I agree, the pre-built should be compatible with any (but E currently) ISA configuration. But we could encourage the user to build the bootloader to their needs and ISA.

:+1:

> This one in bootloader.c:

Oh, right. I forgot about that...

I think we could remove that. It does not capture all possible ISA extensions. So basically it is useless.

> Probably not? [-Oz](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Oz) is even more aggressive, but is currently the same size as -Os.

Interesting! I was not aware of that option. I'll look it up.

> I'll look into it. This would also have the advantage that the bootloader would actually work on all ISA configurations.

I just tested that and it saves more than 100 bytes (yeay!).

-> #1118

> I agree, I'll add that one!

Cool, thanks!

2025-01-07 16:52 UTC, LukasP46 commented
Seems to work on the newest version as well :) only tested without clint/autoboot and only on the two-address-byte eeprom but I haven't noticed any relevant commits anyways.

2025-01-07 20:25 UTC, stnolting commented
This looks great, thank you very much!
I'll have a close look at the code (unfortunately, I do not have a compaitble I²C flash...).

However, I'm not sure about the EEPROM tool. This seems to be quite application-specific, right? 🤔

2025-01-07 20:59 UTC, stnolting requested changes

2025-01-07 20:59 UTC, stnolting commented on sw/bootloader/bootloader.c
> +#ifndef TWI_SLAVE_ID
I suggest renaming this to `TWI_DEVICE_ID` to match the phrases used by the other parts of the code.

2025-01-08 07:50 UTC, LukasP46 commented
> unfortunately, I do not have a compaitble I²C flash...

I suppose there could be FPGA models as well, but no additional testing would be required on my part.

> However, I'm not sure about the EEPROM tool. It is a cool feature and a handy tool, but this seems to be quite application-specific, right?

It kind of is. It should work with all kinds of I2C chips, but yeah, it's only for a weirdly specific USB adapter. I'll remove it from the branch then.

> I suggest renaming this to TWI_DEVICE_ID to match the phrases used by the other parts of the code.

I agree :)

2025-01-08 16:31 UTC, LukasP46 commented
Now the renaming should have an end, sorry for alle the different commits :) feel free to squash

2025-01-08 20:31 UTC, stnolting requested changes

2025-01-08 20:31 UTC, stnolting commented on docs/userguide/customizing_the_bootloader.adoc
> +| `TWI_EN`                | `0` | `0`, `1`      | Set `1` to enable the usage of the SPI module (including load/store executables from/to SPI flash options)
The description should be "Set `1` to enable the usage of the **TWI** module (including loade executables from TWI flash option)" I think.

2025-01-08 20:31 UTC, stnolting commented on docs/userguide/customizing_the_bootloader.adoc
> +| `TWI_ADDR_BYTES`  | `1` | `1`, `2` | TWI memory address size in number of bytes. When `TWI_ADDR_BYTES` is `1`, `TWI_DEVICE_ID` the gets incremented as well.
That's a cool feature! :+1:

2025-01-08 20:31 UTC, stnolting commented on docs/userguide/executable_upload.adoc
> +The bootloader also supports booting from external TWI memory. Enable it in the bootloader makefile, but be caution, enabling all features might result in a too-big binary.
typo: "but be careful"

2025-01-08 20:31 UTC, stnolting commented on sw/bootloader/bootloader.c
> +  EXE_STREAM_TWI   = 2  /**< Get executable via I2c Device */
Let's also use the term "TWI" here

2025-01-08 20:31 UTC, stnolting commented on sw/bootloader/bootloader.c
> +  "FLSH",
Maybe we should change this to "SPI" to make the error more clear.... 🤔

2025-01-08 20:32 UTC, stnolting commented
This looks great! I just have some minor comments. :wink:

By the way... How about also adding an option to store an image to TWI memory (similar to the SPI programming option)?

2025-01-09 08:08 UTC, LukasP46 commented on sw/bootloader/bootloader.c
> +        #endif
That's right for autobooting. 

I thought anyone with SPI flash would prefer it to any I2C memory, but this could be configurable. Just another `#define` with the desired `EXE_STREAM_SOURCE_enum`. And a check, I guess, if the selected option is available. What do you think?

2025-01-09 08:18 UTC, LukasP46 commented
> This looks great! I just have some minor comments. 😉

Thanks! And also thanks for the suggestions.

> By the way... How about also adding an option to store an image to TWI memory (similar to the SPI programming option)?

I actually already answered this (https://github.com/stnolting/neorv32/pull/1108#issuecomment-2535221706), but no worries.  I don't have a use case right now, but I'm keeping it in mind. Probably not in this PR though.

2025-01-10 05:58 UTC, Scutua approved these changes

2025-01-10 05:59 UTC, Scutua approved these changes

2025-01-10 10:12 UTC, LukasP46 commented
There might be problem with CLINT enabled, I need to run some tests...

2025-01-10 10:23 UTC, stnolting commented on sw/bootloader/bootloader.c
> +        #endif
> I thought anyone with SPI flash would prefer it to any I2C memory,

Good point. Besides that, you would adapt the configuration of the bootloader to the hardware setup anyway.

2025-01-10 10:24 UTC, stnolting approved these changes

2025-01-10 10:37 UTC, LukasP46 commented
Maybe an additional Test would be nice where the bootloader get's compiled with the new options as there aren't as default?

2025-01-10 10:48 UTC, Scutua commented on docs/userguide/customizing_the_bootloader.adoc
> +| `TWI_EN`                | `0` | `0`, `1`      | Set `1` to enable the usage of the SPI module (including load/store executables from/to SPI flash options)
Thank you very much boss

2025-01-10 11:04 UTC, merged